version: "3"
services:
  haproxy:
    image: dockercloud/haproxy
    ports:
      - 8012:80
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  hello:
    image: dockercloud/hello-world
    depends_on:
      - haproxy
    networks:
      - proxy
    environment:
      SERVICE_PORTS: "80"

networks:
  proxy:
    driver: overlay
